almuerzos_uv/urls.py
# almuerzos_uv/urls.py


from django.urls import path
from . import views

app_name = 'almuerzos_uv'

urlpatterns = [
    path('registrar/', views.registrar_almuerzo, name='registrar_almuerzo'),
    path('registrar_estudiante/', views.registrar_estudiante, name='registrar_estudiante'),
    path('lista_estudiantes/', views.lista_estudiantes, name='lista_estudiantes'),
    path('index_almuerzos/', views.index_almuerzos, name='index_almuerzos'),
]

nortecaucauv/urls.py
# nortecaucauv/urls.py

from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('almuerzos/', include('almuerzos_uv.urls')),
    #path('almuerzos/', include('almuerzos_uv.urls')),
    #vista para index
    ##path('', index, name='index'),
    ##path('', views.index, name='index'),

    path('', views.home, name='home'),  # Añadir esta línea para la página de inicio
]

almuerzos_uv/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Almuerzo(models.Model):
    fecha = models.DateField(default=timezone.now)
    cantidad = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.fecha} - {self.cantidad} almuerzos"
    


class Estudiante(models.Model):
    codigo_estudiante = models.CharField(max_length=20, unique=True)
    nombre_estudiante = models.CharField(max_length=50)
    apellido_estudiante = models.CharField(max_length=50)
    plan_estudiante = models.CharField(max_length=50)
    correo_estudiante = models.EmailField()

    def __str__(self):
        return f"{self.nombre_estudiante} {self.apellido_estudiante}"

almuerzos_uv/forms.py
# almuerzos_uv/forms.py

from django import forms
from .models import Almuerzo

class AlmuerzoForm(forms.ModelForm):
    class Meta:
        model = Almuerzo
        fields = ['cantidad']


# almuerzos_uv/forms.py

from django import forms
from .models import Estudiante

class EstudianteForm(forms.ModelForm):
    class Meta:
        model = Estudiante
        fields = ['codigo_estudiante', 'nombre_estudiante', 'apellido_estudiante', 'plan_estudiante', 'correo_estudiante']

almuerzos_uv/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from .forms import AlmuerzoForm
from .models import Estudiante
# Create your views here.

def registrar_almuerzo(request):
    if request.method == 'POST':
        form = AlmuerzoForm(request.POST)
        if form.is_valid():
            almuerzo = form.save(commit=False)
            almuerzo.fecha = timezone.now().date()  # Asigna la fecha actual automáticamente
            almuerzo.save()
            return redirect('almuerzos_uv:registrar_almuerzo')  # Redirige a la misma página después de guardar
    else:
        form = AlmuerzoForm()
    return render(request, 'almuerzos_uv/registrar_almuerzo.html', {'form': form})


# almuerzos_uv/views.py

from django.shortcuts import render, redirect
from .forms import EstudianteForm

def registrar_estudiante(request):
    if request.method == 'POST':
        form = EstudianteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('almuerzos_uv:registrar_estudiante')
    else:
        form = EstudianteForm()
    return render(request, 'almuerzos_uv/registrar_estudiante.html', {'form': form})


def lista_estudiantes(request):
    estudiantes = Estudiante.objects.all()
    return render(request, 'almuerzos_uv/lista_estudiantes.html', {'estudiantes': estudiantes})

def index_almuerzos(request):
    return render(request, 'almuerzos_uv/index.html')

nortecaucauv/views.py
# nortecaucauv/views.py

from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request, 'almuerzos_uv/index.html')


def index(request):
    return render(request, 'almuerzos_uv/index.html')

almuerzos_uv/templates/almuerzos_uv/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>INDEX PPAL ALMUERZOS</h1>
</body>
</html>

almuerzos_uv/templates/almuerzos_uv/lista_estudiantes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista Esudiantes</title>
</head>
<body>
    <h1>Lista de Estudiantes</h1>
    <table>
        <thead>
            <tr>
                <th>Código</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Plan</th>
                <th>Correo</th>
            </tr>
        </thead>
        <tbody>
            {% for estudiante in estudiantes %}
            <tr>
                <td>{{ estudiante.codigo_estudiante }}</td>
                <td>{{ estudiante.nombre_estudiante }}</td>
                <td>{{ estudiante.apellido_estudiante }}</td>
                <td>{{ estudiante.plan_estudiante }}</td>
                <td>{{ estudiante.correo_estudiante }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

almuerzos_uv/templates/almuerzos_uv/registrar_almuerzo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrar Almuerzo</title>
</head>
<body>
    <h1>Registrar Almuerzo</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Aceptar</button>
    </form>
</body>
</html>

almuerzos_uv/templates/almuerzos_uv/registrar_estudiante.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrar Estudiante</title>
</head>
<body>
    <h1>Registrar Estudiante</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Aceptar</button>
    </form>
    <br>
    <a href="{% url 'almuerzos_uv:lista_estudiantes' %}">Ver Estudiantes Registrados</a>
</body>
</html>